[tool.poetry]
name = "mmt_multipole_inversion"
version = "0.9"
description = "Library to generate scan grid measurements from multipole sources and perform numerical inversions"
authors = ["D. Cortés-Ortuño <d.i.cortes@uu.nl>", "K. Fabian", "L. V. de Groot"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
numpy = "^1.20,<1.22"
scipy = "^1.7.0"
matplotlib = "^3.2"
numba = ">=0.55"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["setuptools", "poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
